# Generated by Django 5.1 on 2024-09-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('delivered', 'Доставлен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=255, verbose_name='Адрес доставки'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
